### ISSUE TITLE
Missing Trie node

### ISSUE THREAD

**Issue by TimothyDalbey** [compound-developers/compound-borrow-examples#1]
Thanks for writing this up.  When executing the mint-testnet-dai.js script I get the following:  

` Returned error: Returned error: missing trie node 54915a85800f70c7fb4c23667acb68b42848d09f433150af6c692336473eb4d8 (path )`

Any idea how to resolve this?

**Comment by TimothyDalbey** [comment]
Also -  note that this is being thrown when the balance of the DAI contract is retrieved here:
`return daiContract.methods.balanceOf(accounts[0]).call();`

**Comment by ajb413** [comment]
If you're using Cloudflare as an HTTP provider, try using a different HTTP provider, like Infura.io.

**Comment by TimothyDalbey** [comment]
The command that I'm using is

```compound-borrow % ./node_modules/.bin/ganache-cli \
  -f https://cloudflare-eth.com/ \
  -m "clutch captain shoe salt awake harvest setup primary inmate ugly among become" \
  -i 999 \
  -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28```

Are you suggesting that I fork from Infuria.io?

**Comment by ajb413** [comment]
right

**Comment by TimothyDalbey** [comment]
OK -  that did produce successful results in the limited test cases that I used it in.  I wonder if it's worth saving people some time by updating the repo/article to reflect this issue?

**Comment by ajb413** [comment]
Cloudflare works intermittently. It's nice that you don't have to sign up to use their gateway unlike Infura. I'll add a note in the readme.

**Comment by TimothyDalbey** [comment]
Unfortunately, using https://infuria.io blocks the execution of other scripts (including the supply script that is required in most of these examples) as Infuria.io only provides historical data for paid accounts, as I understand things.

**Comment by ajb413** [comment]
100% of the examples in this repo can be run with a free account/project key from Infura to fork a chain with ganache-cli. If you are getting history errors try restarting ganache-cli.
