### ISSUE TITLE
Error when borrowing more than thousand units 

### ISSUE THREAD

**Issue by Miz009** [compound-developers/compound-borrow-examples#13]
Running a local fork and getting the following error when borrowing anything above 4 or 5 units.

ERROR: Error: invalid BigNumber string (argument="value", value="1e+21", code=INVALID_ARGUMENT, version=bignumber/5.4.2)

reason: 'invalid BigNumber string',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '1e+21'

Tested the following:

examples-js > web3-js > borrow-erc20-with-eth-collateral.js
examples-js > ethers-js > borrow-erc20-with-eth-collateral.js

**Comment by ajb413** [comment]
Hi there. Discord #development channel is the best place to ask for help with questions like this (https://compound.finance/discord). Perhaps try passing a string with the full fidelity of the integer? like this: `"1000000000000000000000"`

**Comment by Miz009** [comment]
Thank you Adam, will join the discord and ask there again. FYI tried I tried your suggestion, unfortunately it didn't work for me.
